In [1]:
import pandas as pd

In [2]:
df=pd.read_csv("https://drive.google.com/uc?id=1aZNLCVO0VoHmvPNvSC2teeFmZfiViE6u&export=download")

In [3]:
df

,Index,Name,Description,Brand,Category,Price,Currency,Stock,EAN,Color,Size,Availability,Internal ID
0,1,Thermostat Drone Heater,Consumer approach woman us those star.,Bradford-Yu,Kitchen Appliances,74,USD,139,8619793560985,Orchid,Medium,backorder,38
1,2,Ultra Speaker Iron Grill Advanced One,Point suggest easy money operation could white.,Douglas Group,Fitness Equipment,510,USD,351,3057216124300,MediumSeaGreen,Small,backorder,27
2,3,Watch Headphones Kettle,Reach husband education.,Landry-Austin,Beauty & Personal Care,254,USD,409,9825254410556,Lavender,XXL,pre_order,2
3,4,Portable Toaster Clock Monitor Silent,Always choose school poor table main.,"Odom, Norton and Foster",Makeup,69,USD,119,9490814777808,Pink,XL,in_stock,94
4,5,Pro Toaster Oven,Worry put discuss easy back too career.,"Fowler, Mendoza and Mcdaniel",Automotive,525,USD,727,4726650403799,LightCoral,XL,in_stock,95
...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,996,Silent Router Phone Portable Automatic,Piece the fight near never once bank.,Huffman Group,Toys & Games,903,USD,737,8227581307423,MediumAquaMarine,XL,limited_stock,33
996,997,Digital Treadmill Clean Go,Apply drive outside reach apply.,Woodward Group,Toys & Games,8,USD,330,522633507294,PaleVioletRed,Medium,out_of_stock,9
997,998,Wireless Vacuum Shaver,Line cup course student each about.,Ramos-Cardenas,Beauty & Personal Care,615,USD,630,1892829625606,PaleVioletRed,Extra Large,pre_order,4
998,999,Portable Cooker Brush 360 Digital Mini,History feel worry painting only power bad.,Hooper-Bender,Men's Clothing,811,USD,566,1683591150065,LightGreen,S,in_stock,65
999,1000,Smart Watch Edge Digital Sense,Pay image either rest.,Campos Inc,Kitchen Appliances,867,USD,769,8697154897673,Gainsboro,50x70 cm,limited_stock,10

In [4]:
df.head()

,Index,Name,Description,Brand,Category,Price,Currency,Stock,EAN,Color,Size,Availability,Internal ID
0,1,Thermostat Drone Heater,Consumer approach woman us those star.,Bradford-Yu,Kitchen Appliances,74,USD,139,8619793560985,Orchid,Medium,backorder,38
1,2,Ultra Speaker Iron Grill Advanced One,Point suggest easy money operation could white.,Douglas Group,Fitness Equipment,510,USD,351,3057216124300,MediumSeaGreen,Small,backorder,27
2,3,Watch Headphones Kettle,Reach husband education.,Landry-Austin,Beauty & Personal Care,254,USD,409,9825254410556,Lavender,XXL,pre_order,2
3,4,Portable Toaster Clock Monitor Silent,Always choose school poor table main.,"Odom, Norton and Foster",Makeup,69,USD,119,9490814777808,Pink,XL,in_stock,94
4,5,Pro Toaster Oven,Worry put discuss easy back too career.,"Fowler, Mendoza and Mcdaniel",Automotive,525,USD,727,4726650403799,LightCoral,XL,in_stock,95

In [5]:
df.tail()

,Index,Name,Description,Brand,Category,Price,Currency,Stock,EAN,Color,Size,Availability,Internal ID
995,996,Silent Router Phone Portable Automatic,Piece the fight near never once bank.,Huffman Group,Toys & Games,903,USD,737,8227581307423,MediumAquaMarine,XL,limited_stock,33
996,997,Digital Treadmill Clean Go,Apply drive outside reach apply.,Woodward Group,Toys & Games,8,USD,330,522633507294,PaleVioletRed,Medium,out_of_stock,9
997,998,Wireless Vacuum Shaver,Line cup course student each about.,Ramos-Cardenas,Beauty & Personal Care,615,USD,630,1892829625606,PaleVioletRed,Extra Large,pre_order,4
998,999,Portable Cooker Brush 360 Digital Mini,History feel worry painting only power bad.,Hooper-Bender,Men's Clothing,811,USD,566,1683591150065,LightGreen,S,in_stock,65
999,1000,Smart Watch Edge Digital Sense,Pay image either rest.,Campos Inc,Kitchen Appliances,867,USD,769,8697154897673,Gainsboro,50x70 cm,limited_stock,10

In [6]:
df.describe()

             Index        Price        Stock           EAN  Internal ID
count  1000.000000  1000.000000  1000.000000  1.000000e+03  1000.000000
mean    500.500000   506.549000   501.782000  5.130255e+12    47.690000
std     288.819436   283.773556   292.151318  2.907413e+12    28.984202
min       1.000000     1.000000     2.000000  4.842647e+08     1.000000
25%     250.750000   284.750000   243.000000  2.699217e+12    22.000000
50%     500.500000   497.500000   504.000000  5.118167e+12    46.000000
75%     750.250000   757.250000   750.250000  7.653439e+12    74.000000
max    1000.000000   999.000000   999.000000  9.994627e+12    99.000000

In [7]:
df.isnull()

,Index,Name,Description,Brand,Category,Price,Currency,Stock,EAN,Color,Size,Availability,Internal ID
0,False,False,False,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,False,False,False,False,False,False,False,False,False,False,False,False,False
996,False,False,False,False,False,False,False,False,False,False,False,False,False
997,False,False,False,False,False,False,False,False,False,False,False,False,False
998,False,False,False,False,False,False,False,False,False,False,False,False,False
999,False,False,False,False,False,False,False,False,False,False,False,False,False

In [8]:
df.isnull().sum()

Index           0
Name            0
Description     0
Brand           0
Category        0
Price           0
Currency        0
Stock           0
EAN             0
Color           0
Size            0
Availability    0
Internal ID     0
dtype: int64

In [9]:
df.shape

(1000, 13)

In [10]:
df.size

13000

In [11]:
df.dtypes

Index            int64
Name            object
Description     object
Brand           object
Category        object
Price            int64
Currency        object
Stock            int64
EAN              int64
Color           object
Size            object
Availability    object
Internal ID      int64
dtype: object

In [12]:
df['Size'].unique()

array(['Medium', 'Small', 'XXL', 'XL', 'Extra Large', '5x7 in', 'S',
       '12x18 in', 'M', 'L', 'Large', '50x70 cm', '10x10 cm', '8x10 in',
       '100x200 mm', 'XS', '15x20 cm', '30x40 cm'], dtype=object)

In [13]:
df['Size']=df['Size'].astype('category')

In [14]:
df.dtypes

Index              int64
Name              object
Description       object
Brand             object
Category          object
Price              int64
Currency          object
Stock              int64
EAN                int64
Color             object
Size            category
Availability      object
Internal ID        int64
dtype: object

In [15]:
df

,Index,Name,Description,Brand,Category,Price,Currency,Stock,EAN,Color,Size,Availability,Internal ID
0,1,Thermostat Drone Heater,Consumer approach woman us those star.,Bradford-Yu,Kitchen Appliances,74,USD,139,8619793560985,Orchid,Medium,backorder,38
1,2,Ultra Speaker Iron Grill Advanced One,Point suggest easy money operation could white.,Douglas Group,Fitness Equipment,510,USD,351,3057216124300,MediumSeaGreen,Small,backorder,27
2,3,Watch Headphones Kettle,Reach husband education.,Landry-Austin,Beauty & Personal Care,254,USD,409,9825254410556,Lavender,XXL,pre_order,2
3,4,Portable Toaster Clock Monitor Silent,Always choose school poor table main.,"Odom, Norton and Foster",Makeup,69,USD,119,9490814777808,Pink,XL,in_stock,94
4,5,Pro Toaster Oven,Worry put discuss easy back too career.,"Fowler, Mendoza and Mcdaniel",Automotive,525,USD,727,4726650403799,LightCoral,XL,in_stock,95
...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,996,Silent Router Phone Portable Automatic,Piece the fight near never once bank.,Huffman Group,Toys & Games,903,USD,737,8227581307423,MediumAquaMarine,XL,limited_stock,33
996,997,Digital Treadmill Clean Go,Apply drive outside reach apply.,Woodward Group,Toys & Games,8,USD,330,522633507294,PaleVioletRed,Medium,out_of_stock,9
997,998,Wireless Vacuum Shaver,Line cup course student each about.,Ramos-Cardenas,Beauty & Personal Care,615,USD,630,1892829625606,PaleVioletRed,Extra Large,pre_order,4
998,999,Portable Cooker Brush 360 Digital Mini,History feel worry painting only power bad.,Hooper-Bender,Men's Clothing,811,USD,566,1683591150065,LightGreen,S,in_stock,65
999,1000,Smart Watch Edge Digital Sense,Pay image either rest.,Campos Inc,Kitchen Appliances,867,USD,769,8697154897673,Gainsboro,50x70 cm,limited_stock,10

In [163]:
df['Availability'].unique()

array(['backorder', 'pre_order', 'in_stock', 'out_of_stock',
       'limited_stock', 'discontinued'], dtype=object)

In [164]:
df['new_Availability']=df['Availability'].map({'backorder':0,'pre_order':1,'in_stock':2,'out_of_stock':3,'limited_stock':4,'discounted':5})

In [165]:
df

,Index,Name,Description,Brand,Category,Price,Currency,Stock,EAN,Color,Size,Availability,Internal ID,new_Availability
0,1,Thermostat Drone Heater,Consumer approach woman us those star.,Bradford-Yu,Kitchen Appliances,74,USD,139,8619793560985,Orchid,Medium,backorder,38,0.0
1,2,Ultra Speaker Iron Grill Advanced One,Point suggest easy money operation could white.,Douglas Group,Fitness Equipment,510,USD,351,3057216124300,MediumSeaGreen,Small,backorder,27,0.0
2,3,Watch Headphones Kettle,Reach husband education.,Landry-Austin,Beauty & Personal Care,254,USD,409,9825254410556,Lavender,XXL,pre_order,2,1.0
3,4,Portable Toaster Clock Monitor Silent,Always choose school poor table main.,"Odom, Norton and Foster",Makeup,69,USD,119,9490814777808,Pink,XL,in_stock,94,2.0
4,5,Pro Toaster Oven,Worry put discuss easy back too career.,"Fowler, Mendoza and Mcdaniel",Automotive,525,USD,727,4726650403799,LightCoral,XL,in_stock,95,2.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,996,Silent Router Phone Portable Automatic,Piece the fight near never once bank.,Huffman Group,Toys & Games,903,USD,737,8227581307423,MediumAquaMarine,XL,limited_stock,33,4.0
996,997,Digital Treadmill Clean Go,Apply drive outside reach apply.,Woodward Group,Toys & Games,8,USD,330,522633507294,PaleVioletRed,Medium,out_of_stock,9,3.0
997,998,Wireless Vacuum Shaver,Line cup course student each about.,Ramos-Cardenas,Beauty & Personal Care,615,USD,630,1892829625606,PaleVioletRed,Extra Large,pre_order,4,1.0
998,999,Portable Cooker Brush 360 Digital Mini,History feel worry painting only power bad.,Hooper-Bender,Men's Clothing,811,USD,566,1683591150065,LightGreen,S,in_stock,65,2.0
999,1000,Smart Watch Edge Digital Sense,Pay image either rest.,Campos Inc,Kitchen Appliances,867,USD,769,8697154897673,Gainsboro,50x70 cm,limited_stock,10,4.0

In [166]:
df.dtypes

Index                  int64
Name                  object
Description           object
Brand                 object
Category              object
Price                  int64
Currency              object
Stock                  int64
EAN                    int64
Color                 object
Size                category
Availability          object
Internal ID            int64
new_Availability     float64
dtype: object