In [3]:
import pandas as pd 

import matplotlib.pyplot as plt

In [4]:
df = pd.read_csv('StudentsPerformance.csv')
df

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score
0,female,group B,bachelor's degree,standard,none,72,72,74
1,female,group C,some college,standard,completed,69,90,88
2,female,group B,master's degree,standard,none,90,95,93
3,male,group A,associate's degree,free/reduced,none,47,57,44
4,male,group C,some college,standard,none,76,78,75
...,...,...,...,...,...,...,...,...
995,female,group E,master's degree,standard,completed,88,99,95
996,male,group C,high school,free/reduced,none,62,55,55
997,female,group C,high school,free/reduced,completed,59,71,65
998,female,group D,some college,standard,completed,68,78,77
999,female,group D,some college,free/reduced,none,77,86,86

In [5]:
df.isnull().sum()

gender                         0
race/ethnicity                 0
parental level of education    0
lunch                          0
test preparation course        0
math score                     0
reading score                  0
writing score                  0
dtype: int64

In [6]:
df.dropna()

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score
0,female,group B,bachelor's degree,standard,none,72,72,74
1,female,group C,some college,standard,completed,69,90,88
2,female,group B,master's degree,standard,none,90,95,93
3,male,group A,associate's degree,free/reduced,none,47,57,44
4,male,group C,some college,standard,none,76,78,75
...,...,...,...,...,...,...,...,...
995,female,group E,master's degree,standard,completed,88,99,95
996,male,group C,high school,free/reduced,none,62,55,55
997,female,group C,high school,free/reduced,completed,59,71,65
998,female,group D,some college,standard,completed,68,78,77
999,female,group D,some college,free/reduced,none,77,86,86

In [8]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()

df['sex_encoded'] = le.fit_transform(df['gender'])  # male=1, female=0
df

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score,sex_encoded
0,female,group B,bachelor's degree,standard,none,72,72,74,0
1,female,group C,some college,standard,completed,69,90,88,0
2,female,group B,master's degree,standard,none,90,95,93,0
3,male,group A,associate's degree,free/reduced,none,47,57,44,1
4,male,group C,some college,standard,none,76,78,75,1
...,...,...,...,...,...,...,...,...,...
995,female,group E,master's degree,standard,completed,88,99,95,0
996,male,group C,high school,free/reduced,none,62,55,55,1
997,female,group C,high school,free/reduced,completed,59,71,65,0
998,female,group D,some college,standard,completed,68,78,77,0
999,female,group D,some college,free/reduced,none,77,86,86,0

In [6]:
newdf=df[(df['math score'] > 40)&
         (df['reading score'] > 40) &
         (df['writing score'] > 40)]
newdf

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score
0,female,group B,bachelor's degree,standard,none,72,72,74
1,female,group C,some college,standard,completed,69,90,88
2,female,group B,master's degree,standard,none,90,95,93
3,male,group A,associate's degree,free/reduced,none,47,57,44
4,male,group C,some college,standard,none,76,78,75
...,...,...,...,...,...,...,...,...
995,female,group E,master's degree,standard,completed,88,99,95
996,male,group C,high school,free/reduced,none,62,55,55
997,female,group C,high school,free/reduced,completed,59,71,65
998,female,group D,some college,standard,completed,68,78,77
999,female,group D,some college,free/reduced,none,77,86,86

In [7]:
newdf['gender'].unique()

array(['female', 'male'], dtype=object)

In [11]:
female_count  =(newdf['gender'] == 'female').sum()
male_count  =(newdf['gender'] == 'male').sum()

female_count > male_count

np.True_

In [13]:
df['gender'].replace({'male': 1 , 'female': 0} , inplace= True)
df

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score
0,0,group B,bachelor's degree,standard,none,72,72,74
1,0,group C,some college,standard,completed,69,90,88
2,0,group B,master's degree,standard,none,90,95,93
3,1,group A,associate's degree,free/reduced,none,47,57,44
4,1,group C,some college,standard,none,76,78,75
...,...,...,...,...,...,...,...,...
995,0,group E,master's degree,standard,completed,88,99,95
996,1,group C,high school,free/reduced,none,62,55,55
997,0,group C,high school,free/reduced,completed,59,71,65
998,0,group D,some college,standard,completed,68,78,77
999,0,group D,some college,free/reduced,none,77,86,86

In [17]:
df.groupby(['race/ethnicity' ,'parental level of education'])

In [19]:
df['total score'] = df['math score'] + df['reading score'] + df['writing score']
df

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score,total score
0,0,group B,bachelor's degree,standard,none,72,72,74,218
1,0,group C,some college,standard,completed,69,90,88,247
2,0,group B,master's degree,standard,none,90,95,93,278
3,1,group A,associate's degree,free/reduced,none,47,57,44,148
4,1,group C,some college,standard,none,76,78,75,229
...,...,...,...,...,...,...,...,...,...
995,0,group E,master's degree,standard,completed,88,99,95,282
996,1,group C,high school,free/reduced,none,62,55,55,172
997,0,group C,high school,free/reduced,completed,59,71,65,195
998,0,group D,some college,standard,completed,68,78,77,223
999,0,group D,some college,free/reduced,none,77,86,86,249

In [22]:
df.sort_values(by='math score', ascending=True).head(50)

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score,total score
59,0,group C,some high school,free/reduced,none,0,17,10,27
980,0,group B,high school,free/reduced,none,8,24,23,55
17,0,group B,some high school,free/reduced,none,18,32,28,78
787,0,group B,some college,standard,none,19,38,32,89
145,0,group C,some college,free/reduced,none,22,39,33,94
842,0,group B,high school,free/reduced,completed,23,44,36,103
338,0,group B,some high school,free/reduced,none,24,38,27,89
466,0,group D,associate's degree,free/reduced,none,26,31,38,95
363,0,group D,some high school,free/reduced,none,27,34,32,93
91,1,group C,high school,free/reduced,none,27,34,36,97
327,1,group A,some college,free/reduced,none,28,23,19,70
683,0,group C,some high school,free/reduced,completed,29,40,44,113
528,0,group D,bachelor's degree,free/reduced,none,29,41,47,117
601,0,group C,high school,standard,none,29,29,30,88
596,1,group B,high school,free/reduced,none,30,24,15,69
76,1,group E,some high school,standard,none,30,26,22,78
555,0,group C,some college,free/reduced,none,32,39,33,104
785,0,group B,some high school,standard,completed,32,51,44,127
895,0,group E,some high school,free/reduced,none,32,34,38,104
55,0,group C,high school,free/reduced,none,33,41,43,117
217,0,group C,high school,free/reduced,none,34,42,39,115
902,0,group A,high school,free/reduced,completed,34,48,41,123
620,0,group C,high school,free/reduced,none,35,61,54,150
211,1,group C,some college,free/reduced,none,35,28,27,90
777,0,group C,some college,free/reduced,none,35,44,43,122
921,0,group C,high school,free/reduced,none,35,53,46,134
339,0,group D,some high school,free/reduced,completed,35,55,60,150
896,1,group B,high school,free/reduced,none,36,29,27,92
527,0,group C,high school,free/reduced,none,36,53,43,132
455,1,group C,bachelor's degree,free/reduced,none,37,56,47,140
284,0,group B,some high school,standard,none,37,46,46,129
741,0,group A,associate's degree,free/reduced,none,37,57,56,150
616,0,group E,bachelor's degree,standard,none,37,45,38,120
383,0,group E,some high school,free/reduced,none,38,49,45,132
9,0,group B,high school,free/reduced,none,38,60,50,148
384,0,group A,some high school,free/reduced,none,38,43,43,124
862,1,group D,bachelor's degree,free/reduced,completed,39,42,38,119
840,0,group D,high school,free/reduced,none,39,52,46,137
61,1,group A,some high school,free/reduced,none,39,39,34,112
69,0,group C,associate's degree,standard,none,39,64,57,160
7,1,group B,some college,free/reduced,none,40,43,39,122
844,0,group D,some high school,free/reduced,completed,40,65,64,169
33,1,group D,some college,standard,none,40,42,38,120
607,0,group C,master's degree,free/reduced,none,40,58,54,152
552,0,group B,associate's degree,standard,none,40,48,50,138
298,1,group C,high school,free/reduced,completed,40,46,50,136
504,0,group D,master's degree,free/reduced,none,40,59,54,153
575,1,group A,associate's degree,free/reduced,completed,40,55,53,148
986,0,group C,associate's degree,standard,none,40,59,51,150
11,1,group D,associate's degree,standard,none,40,52,43,135